#!/usr/bin/python3
def complex_delete(a_dictionary, value):
    flag = True
    if value:
        while flag:
            for key in a_dictionary:
                if a_dictionary[key] == value:
                    del a_dictionary[key]
                break
            flag = False
    return a_dictionary
